### ISSUE TITLE
 django.db.utils.OperationalError: no such table: verticalsearch_reddituser

### ISSUE THREAD

**Issue by pyrl247** [assalw/DSS#1]
I try to run the server,when it comes to the crawling step,it tells me '' django.db.utils.OperationalError: no such table: verticalsearch_reddituser''. I check the django models and items ,there is no verticalsearch_reddituser class. what is wrong? python traceback to the step item.save() in pipelines.py line 18.

**Comment by assalw** [comment]
Hi Alsjfk,

Thank you for raising the issue. Please create your database with the following command:

`python manage.py syncdb`

It should be run from the project root. Let me know if this resolves the issue for you.

**Comment by assalw** [comment]
No response. Closing the issue.
